### ISSUE TITLE
[Feature request] Add Android App Bundle (.aab) on GitHub Releases.

### ISSUE THREAD

**Issue by ratatouille100** [StarGW-net/karma-firewall#21]
[About Android App Bundles](https://developer.android.com/guide/app-bundle)

[How to build an app bundle?](https://medium.com/androiddevelopers/building-your-first-app-bundle-bbcd228bf631)

**Comment by StarGW-net** [comment]
The main benefit of App Bundles is: "optimize support for different devices, and users get smaller, more-optimized downloads."

Karma is only 1.55 MB so its pretty small already, mainly because I avoid third party frameworks and libraries that so much software seems to rely on these days.

https://liam-on-linux.dreamwidth.org/88032.html
